#!/bin/sh

DAY=$1

touch data/day${DAY}.txt
touch data/day${DAY}_test.txt

SRC="src/day${DAY}.js"

touch $SRC

echo "const Loader = require('./loader')" >> $SRC
echo "const SolverBase = require('./solver_base')" >> $SRC
echo "" >> $SRC
echo "" >> $SRC
echo "class SolverDay${DAY} extends SolverBase {" >> $SRC
echo "  constructor(testData = false) {" >> $SRC
echo "    super('${DAY}', testData)" >> $SRC
echo "  }" >> $SRC
echo "" >> $SRC
echo "" >> $SRC
echo "  loadData() {" >> $SRC
echo "" >> $SRC
echo "  }" >> $SRC
echo "" >> $SRC
echo "" >> $SRC
echo "  puzzle1() {" >> $SRC
echo "" >> $SRC
echo "  }" >> $SRC
echo "" >> $SRC
echo "" >> $SRC
echo "  puzzle2() {" >> $SRC
echo "" >> $SRC
echo "  }" >> $SRC
echo "}" >> $SRC
echo "" >> $SRC
echo "" >> $SRC
echo "module.exports = SolverDay${DAY}" >> $SRC
